---

 - name: Add cartodb postgresql apt repository
   apt_repository: repo=ppa:cartodb/postgresql-{{ postgresql_version }} update_cache=yes

 - name: Install postgresql client packages
   apt: name={{ item }} state=present
   with_items:
    - libpq5
    - libpq-dev
    - python-psycopg2
    - postgresql-client-{{ postgresql_version }}
    - postgresql-client-common

 - name: Install postgresql server packages
   apt: name={{ item }} state=present
   with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-contrib-{{ postgresql_version }}
    - postgresql-server-dev-{{ postgresql_version }}
    - postgresql-plpython-{{ postgresql_version }}

 - name: Configure PostgreSQL host-based authentication
   template: src=pg_hba.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
   notify:
     - Restart PostgreSQL

 - name: Configure PostgreSQL conf
   template: src=postgresql.conf.j2 dest=/etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
   notify:
     - Restart PostgreSQL

 # Need to force a restart now so that auth settings take effect for all future tasks
 #   Otherwise, things like `bundle exec rake db:create` will hang asking for a password
 - meta: flush_handlers

 - name: Add cartodb publicuser
   postgresql_user: name=publicuser port={{ postgresql_port }} state=present role_attr_flags=NOCREATEROLE,NOSUPERUSER,NOCREATEDB
   become_user: postgres

 - name: Add cartodb tileuser
   postgresql_user: name=tileuser port={{ postgresql_port }} state=present role_attr_flags=NOCREATEROLE,NOSUPERUSER,NOCREATEDB
   become_user: postgres

 - include: postgis.yml

 - include: cartodb_extension.yml

